# Generated by Django 5.2 on 2025-05-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_remove_medicine_category_medicine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='medicine.category'),
        ),
    ]
