# Generated by Django 5.2 on 2025-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_alter_medicine_manufacturer_delete_manufacturer'),
        ('orders', '0003_remove_cartitem_cart_remove_cartitem_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='orders.OrderItem', to='medicine.medicine'),
        ),
    ]
